config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'search_forms#show'
  post '/', to: 'search_forms#create', as: 'search'
  # resource :avia_search, only: [:show, :create]

  resource :ticket_form, only: [:create]
  resources :tickets, only: [:index] do
    get :destroy_all, on: :collection
  end
end

app/controllers/search_forms_controller.rb
class SearchFormsController < ApplicationController
  def show
    build_resource
  end

  def create
    build_resource
    if @resource.save
      search_result = Gds::GdsSearchService.new.search_flights(@resource)
      # TODO: add errors from search_result.errors to form object
      @flights = search_result.flights
    end
    render 'show'
  end

  private

  def build_resource
    @resource = SearchForm.new(resource_params)
    @resource.build_search_routes(2)
    @resource.search_routes.map! { |search_route| FrontSearchRouteValidation.new(search_route) }
  end

  def resource_params
    resource_params = params[:search_form]
    resource_params = if resource_params
                        resource_params.permit(search_routes_attributes: %i[departure date arrival search_route_id]) # TODO: check allowed params in Policy object (Pundit etc)
                      else
                        {}
                      end
    # ActiveType::Object#nests_many does not support :limit option :(
    resource_params[:search_routes_attributes]&.slice!('0', '1')
    resource_params
  end
end

app/views/search_forms/_flight.html.slim
h4 Flight #{flight_counter+1}

table border="1"
  = render partial: 'flight_route', collection: flight.flight_routes
  tr
    td Total price
    td= flight.price
  tr
    td colspan="2"= link_to 'Book flight', ticket_form_path(flight_uuid: flight.uuid), remote: true, method: :post

app/views/search_forms/_flight_route.html.slim
tr
  td colspan="2" = "#{flight_route_counter+1} route"
tr
  td Aircompany
  td= flight_route.air_company
tr
  td Flight number
  td= flight_route.flight_number
tr
  td Flight time
  td= flight_route.flight_time

tr
  td Departure
  td= flight_route.departure_full
tr
  td Arrival
  td= flight_route.arrival_full

app/views/search_forms/_flights.html.slim
/ - flights.each_with_index do |flight, index|
/   = render partial: 'search_forms/'+flight.class.name.underscore, locals: {flight: flight, flight_counter: index}

= render partial: 'flight', collection: flights

app/views/search_forms/_form.html.slim
= simple_form_for resource, url: search_path, method: :post do |f|
  = f.simple_fields_for :search_routes, input_html: {include_hidden: false} do |fr|
    = fr.input :departure
    = fr.input :arrival
    = fr.input :date
    = fr.input :search_route_id, as: :hidden, input_html: {value: fr.options[:child_index]}
    hr
  = f.submit

app/views/search_forms/show.html.slim
= link_to 'Tickets', tickets_path
h3 search form
= render partial: 'form', locals: {resource: @resource}

hr
#search_result
  | Search results:
  br
  - if @resource.errors
    - @resource.errors.messages.each do |key,values|
      - next if key.to_s.start_with?('search_routes')
      - values.each do |message|
        = "#{key}: #{message}"
      br
  - if @flights.present?
    = render partial: 'flights', locals: {flights: @flights}